---
title: "week 1 peer graded submission"
author: "Nils"
date: "20 September 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Peer graded submission

## 1 plot 1

```{r}
setwd("C:/Users/.../R Programming/Exploratory data analyses/week1")
totalinput <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")



 totalinput$Date <- as.Date(totalinput$Date, "%d/%m/%Y")
# totalinput$Time <- as.POSIXct(strptime(totalinput$Time, "%H:%M:%S"))

```


```{r}
a <- subset(totalinput, totalinput$Date == "2007-02-01")
b <- subset(totalinput, totalinput$Date == "2007-02-02")
work <- rbind(a, b)
rm(a, b, totalinput)
work <- within(work, { timestamp=format(as.POSIXct(paste(Date, Time)), "%d/%m/%Y %H:%M:%S") })
```

```{r}
work$timestamp <- as.POSIXct(strptime(work$timestamp, "%d/%m/%Y %H:%M:%S"))
```


```{r}
plot1 <- hist(work$Global_active_power, main = "Global Active Power", col = "red", xlab = "Global Active Power (kilowatts)")
```

```{r}
png(filename="plot1.png")
plot1 <- hist(work$Global_active_power, main = "Global Active Power", col = "red", xlab = "Global Active Power (kilowatts)")
dev.off()
```

## 2 plot 2

```{r}
png(filename="plot2.png")
plot2 <- plot(x = work$timestamp, y = work$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dev.off()
```

## 3 plot 3

```{r}
png(filename="plot3.png")
plot(x = work$timestamp, y = work$Sub_metering_1, xlab = "", ylab = "Energy sub Metering", type = "l")
points(x=work$timestamp, y=work$Sub_metering_2, col='red', type='l')
points(x=work$timestamp, y=work$Sub_metering_3, col='blue', type='l')
legend('topright', names(work)[7:9] , 
   lty=1, col=c('black', 'red', 'blue'), cex=.75)
dev.off()
```



## 4 plot 4


```{r}
png(filename="plot4.png")
par(mfcol = c(2,2)) 
a <- plot(x = work$timestamp, y = work$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")

b <- plot(x = work$timestamp, y = work$Sub_metering_1, xlab = "", ylab = "Energy sub Metering", type = "l")
points(x=work$timestamp, y=work$Sub_metering_2, col='red', type='l')
points(x=work$timestamp, y=work$Sub_metering_3, col='blue', type='l')
legend('topright', names(work)[7:9] , col=c('black', 'red', 'blue'), cex=.35)

c <- plot(x = work$timestamp, y = work$Voltage, type = "l", xlab = "datetime", ylab = "Global Active Power (kilowatts)")

d <- plot(x = work$timestamp, y = work$Global_active_power, type = "l", xlab = "datetime")
dev.off()
```
















